---
title: "Landscape Table Demo"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
library('tidyverse')
library('mrggt')

```

```{r echo = FALSE}
tbl_colored <- dplyr::tribble( ~grpname, ~count, ~color,
                               'apple', 1, 'red',
                               'banana', 2, 'yellow',
                               'grape', 3, 'purple',
                               'pear', 4, 'green',
                               'orange', 5, 'orange')
```

```{r}

tbl_gt <-
  gt(data = tbl_colored) %>%
  lscape() %>%
  tab_style(
    style = list(cell_text(color = "#ffcccb",
                           weight = 'bold'),
                 cell_fill(color = "#ffffed")),
    locations = cells_body(
      columns = everything(),
      rows = startsWith(grpname, 'a')
    )
  ) %>%
  tab_style(
    style = cell_fill(color = "#ffffed"),
    locations = cells_body(
      columns = everything(),
      rows = startsWith(grpname, 'b')
    )
  ) %>%
  tab_style(
    style = cell_fill(color = "#b19cd9"),
    locations = cells_body(
      columns = everything(),
      rows = startsWith(grpname, 'g')
    )
  ) %>%
  tab_style(
        style = cell_fill(color = "#90ee90"),
        locations = cells_body(
          columns = everything(),
          rows = startsWith(grpname, 'p')
        )
   ) %>%
  tab_style(
    style = cell_fill(color = "#fed8b1"),
    locations = cells_body(
      columns = everything(),
      rows = startsWith(grpname, 'o')
    )
  ) %>%
  cols_label(.list = list(grpname = 'Fruit',
                          count = 'Total',
                          color = 'Color')) %>%
  tab_source_note(c('Source code: /integration_table_tests/lscape_demo.R',
                    'Source code: /integration_table_tests/lscape_demo.tex')) %>%
  as_latex()

readr::write_file(tbl_gt, 'test.tex')
tbl_gt
```


# Multiple Tables on Single Landscape Page
```{r}
tbl_gt + tbl_gt
```
