---
title: "Cell Color + Landscape"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
library('tidyverse')
library('mrggt')
```

```{r}
tbl_colored <- dplyr::tribble( ~grpname, ~count, ~color,
                               'apple', 1, 'red',
                               'banana', 2, 'yellow',
                               'grape', 3, 'purple',
                               'pear', 4, 'green',
                               'orange', 5, 'orange')

tbl_gt <- gt(data = tbl_colored) %>%
  lscape() %>%
  tab_header(title = 'Table 1',
             subtitle = stringi::stri_rand_lipsum(1)) %>%
  tab_style(
    style = cell_fill(color = "#ffcccb"),
    locations = cells_body(columns = everything(),
                           rows = startsWith(grpname, 'a'))
  ) %>%
  tab_style(
    style = cell_fill(color = "#ffffed"),
    locations = cells_body(columns = everything(),
                           rows = startsWith(grpname, 'b'))
  ) %>%
  tab_style(
    style = cell_fill(color = "#b19cd9"),
    locations = cells_body(columns = everything(),
                           rows = startsWith(grpname, 'g'))
  ) %>%
  tab_style(
    style = cell_fill(color = "#90ee90"),
    locations = cells_body(columns = everything(),
                           rows = startsWith(grpname, 'p'))
  ) %>%
  tab_style(
    style = cell_fill(color = "#fed8b1"),
    locations = cells_body(columns = everything(),
                           rows = startsWith(grpname, 'o'))
  ) %>%
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_title('title')
  ) %>%
  tab_style(
    style = cell_text(style = "italic"),
    locations = cells_title('subtitle')
  ) %>%
  cols_label(.list = list(
    grpname = 'Fruit',
    count = 'Total',
    color = 'Color'
  )) %>%
  tab_source_note(
    c(
      paste0('Script code: ', knitr::current_input()),
      paste0('Tex code: ', gsub('.Rmd', '.tex', knitr::current_input()))
    )
  ) %>%
  tab_footnote('something', locations = cells_body(columns = 'grpname',
                           rows = startsWith(grpname, 'o'))) %>%
  tab_footnote('something2', locations = cells_body(columns = 'grpname',
                           rows = startsWith(grpname, 'p'))) %>%

  as_latex()

tbl_gt 

```

# Combine Landscape Tables
```{r echo}
tbl_gt + tbl_gt
```
