latex_s.default <- function(scale_factor,
                            col_lengths){
  col_lengths * scale_factor
}

latex_s.list <- function(scale_factor,
                         col_lengths){

  shrink_at <- unlist(scale_factor)[c(TRUE, FALSE)]
  shrink_by <- unlist(scale_factor)[c(FALSE, TRUE)]
  col_lengths[shrink_at] <- col_lengths[shrink_at] * shrink_by

  col_lengths
}

latex_s <- function(scale_factor,
                    latex_code,
                    align){
  UseMethod('latex_s')
}

#' Scale full table or individual columns for latex table output
#'
#' @param latex_code knit_asis chr string generated by ```as_latex()``` on a gt table object.
#' @param scale_factor proportion to shrink or enlarge. can be a numeric value to scale the full table or a list of vectors in the format ```list(c(column number, scale factor))``` to apply scaling to specific column(s).
#' @param align align direction to align the full table on the page.
#'
#' @examples
#' df <- dplyr::tribble(
#'  ~ fruit, ~ count,  ~ color,
#'  'apple',       1,    'red',
#' 'banana',       2,  'yellow'
#' )
#'
#' # shrink column 1 by 0.5 and column 3 by 0.7.
#' df %>%
#' gt() %>%
#' as_latex() %>%
#' latex_scale(scale_factor = list(c(1, 0.5),
#'                                 c(3, 0.7)))
#'
#' # shrink all the columns by 0.5.
#' df %>%
#' gt() %>%
#' as_latex() %>%
#' latex_scale(scale_factor = 0.5)
#'
#' @export
latex_scale <- function(latex_code,
                        scale_factor,
                        align = c('l', 'r', 'c')) {
  align <- match.arg(align)
  latex_code <- latex_code %>% as.character()

  tex_split <- stringr::str_split(latex_code, '\n') %>%
    unlist()

  #shrink the column widths
  loc <- startsWith(tex_split, '\\begin{longtable}')
  col_lengths <-
    qdapRegex::rm_between(tex_split[loc], 'p{', 'cm}', extract = TRUE) %>%
    unlist() %>%
    as.double()

  col_lengths <- latex_s(scale_factor, col_lengths)
  col_lengths_str <- paste(sprintf('p{%.3fcm}', col_lengths), collapse = '')
  header_align <- paste0("\\begin{longtable}[", align, ']{')

  tex_split[loc]  <- paste0(header_align, col_lengths_str, "}")

  #resize footnotes/title
  loc <- grepl('\\w?\\\\begin\\{minipage\\}', tex_split)
  tex_split[loc] <- paste0('\\begin{minipage}{',
                           sum(col_lengths),
                           'cm}')

  #reize the caption width
  loc <- startsWith(tex_split, '\\setlength\\LTcapwidth')
  tex_split[loc] <- paste0('\\setlength\\LTcapwidth{',
                           sum(col_lengths),
                           'cm}')

  tex_code <- paste(tex_split, collapse = '\n')
  latex_packages <- create_knit_meta(shrink = TRUE)
  tex_code %>% knitr::asis_output(meta = latex_packages)
}

retype <- function(x){
  UseMethod('retype')
}

retype.knit_asis <- function(x){
  list(x)
}

retype.list <- function(x){
  x
}

'+.knit_asis' <- function(a, b){
  c(retype(a), retype(b))
}

#' Orient a LateX table in landscape
#'
#' @param latex_code knit_asis chr string generated by ```as_latex()``` on a gt table object or a list of knit_asis chr strings.
#'
#' @examples
#' df <- dplyr::tribble(
#'  ~ fruit, ~ count,  ~ color,
#'  'apple',       1,    'red',
#' 'banana',       2,  'yellow'
#' )
#'
#' # single table on a single landscape page
#' df %>%
#' gt() %>%
#' as_latex() %>%
#' lscape()
#'
#' # multiple tables on a single landscape page
#' tbl <- df %>%
#'        gt() %>%
#'        as_latex()
#'
#' (tbl + tbl + tbl) %>% lscape()
#'
#'        -- or --
#'
#' list(tbl, tbl, tbl) %>% lscape()
#'
#' @export
lscape <- function(latex_code){
  UseMethod('lscape')
}

lscape.knit_asis <- function(latex_code){
  knit_meta <- attributes(latex_code)$knit_meta
  knit_meta[[4]]$extra_lines <- NULL
  latex_code <- gsub('longtable',
                     'lscape-mrggtab',
                     latex_code %>% as.character(),
                     fixed = TRUE)
  latex_code %>% knitr::asis_output(meta = knit_meta)
}

lscape.list <- function(latex_code){
  knit_meta <- attributes(latex_code[[1]])$knit_meta
  knit_meta[[4]]$extra_lines <- NULL
  grouped_tbls <- paste('\\begin{landscape}',
                        "\\pagestyle{empty}",
                        paste(unlist(lapply(latex_code, as.character)), collapse = '\n'),
                        "\\end{landscape}",
                        sep = '\n')
  grouped_tbls %>% knitr::asis_output(meta = knit_meta)
}
